services:
  web:
    build: .
    command: sh entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - system_network
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: backend_online
      POSTGRES_USER: system
      POSTGRES_PASSWORD: test
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    networks:
      - system_network
    

volumes:
  postgres_data:
networks:
  system_network:
    driver: bridge