# Generated by Django 5.2.1 on 2025-05-26 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la compañía')),
                ('ruc', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='RUC')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, default='', max_length=12, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección')),
                ('primary_color', models.CharField(blank=True, default='', max_length=7, verbose_name='Color primario')),
                ('secondary_color', models.CharField(blank=True, default='', max_length=7, verbose_name='Color secundario')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', related_query_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', related_query_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
