# Generated by Django 5.2.1 on 2025-05-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo electrónico')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('names', models.CharField(blank=True, default='', max_length=50, verbose_name='Nombres')),
                ('surnames', models.CharField(blank=True, default='', max_length=50, verbose_name='Apellidos')),
                ('identification_type', models.CharField(blank=True, choices=[('DNI', 'DNI'), ('CE', 'CARNET DE EXTRANJERIA'), ('PASSPORT', 'PASAPORTE')], max_length=20, verbose_name='Tipo de identificación')),
                ('vat', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de identificación')),
                ('timezone', models.CharField(blank=True, default='', max_length=50, verbose_name='Zona horaria')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-id'],
            },
        ),
    ]
